" Show line number
set number

" Show status and cursor position
set laststatus=2
set ruler

" Enable block select
set virtualedit=block 

" Allow backspacing over everything in insert mode
set backspace=indent,eol,start

" Syntax highlight
syntax on

" Show tab characters. Visual Whitespace.
set list
set listchars=tab:>.

" Select when using the mouse
set selectmode=mouse

" Set ignorecase on
set ignorecase

" smart search (override 'ic' when pattern has uppers)
set scs

" Split screen setup
set splitright
set splitbelow

" Use 4 spaces instead of tabs
set tabstop=4
set expandtab

" Always set auto indenting on
set autoindent

" Highlight search result
set hlsearch

" Color scheme
" All default color exists in /usr/share/vim/vim70/colors
color default 
hi StatusLineNC	cterm=bold ctermbg=blue ctermfg=grey guibg=yellow guifg=blue

" Enable clipboard sharing
set clipboard=unnamed

" Show end of line character
match Error /\s\+$/
